### PR TITLE
Move XF.start from xf.core.js to app/start.js, add test for new module and make related changes.

### PR DESCRIPTION
**Pull request by Jauhen**

### CODE REVIEW

**Comment by Jauhen** [comment]
This is just squashed version of pr#184.

**Comment by pukhalski** [comment]
Hey Jauhen,
could you please fix the test as well?

`
TypeError: Object function require(path) {
    return self.require(path);
  } has no method 'config'
    at Object.<anonymous> (/home/travis/build/epam/xframework/test/main.js:1:71)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /home/travis/build/epam/xframework/node_modules/mocha/lib/mocha.js:157:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/travis/build/epam/xframework/node_modules/mocha/lib/mocha.js:154:14)
    at Mocha.run (/home/travis/build/epam/xframework/node_modules/mocha/lib/mocha.js:341:31)
    at Object.<anonymous> (/home/travis/build/epam/xframework/node_modules/mocha/bin/_mocha:351:7)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3
`

**Comment by Jauhen** [comment]
do you tried "grunt bower" before test run?

**Comment by pukhalski** [comment]
Nope for now. I just found that your PR make build fail. So if you don't mind I will merge and fix the build.

**Comment by pukhalski** [comment]
As well as we need to figure out how to push Travis not to consider builds for PRs as the master builds

**Comment by Jauhen** [comment]
Yes, fix please.

Just don't send pull requests to master, they need to be pushed to
branched. Then tested brunches should go into master.

On 20 December 2013 08:23, Ilya Pukhalski notifications@github.com wrote:

> As well as we need to figure out how to push Travis not to consider builds
> for PRs as the master builds
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/epam/xframework/pull/187#issuecomment-31021339
> .

## 

Best Regards,
    Jauhen

**Comment by Jauhen** [comment]
This test is supposed to be ran by require.js directive, like 

```
<script data-main="main.js" src="../bower_modules/requirejs/require.js"></script>
```

but Travis just run file as is, without using require.js.

**Pull request merged**
